(test
 (name hunt_balance_list_tree)
 (modules hunt_balance_list_tree)
 (libraries core core_kernel.nonempty_list unix base_quickcheck
   splittable_random tape_engine balance_list_tree)
 (preprocess
  (pps base_quickcheck.ppx_quickcheck ppx_sexp_conv ppx_compare ppx_let)))

(test
 (name hunt_trampoline)
 (modules hunt_trampoline)
 (libraries core core_kernel.nonempty_list unix base_quickcheck
   splittable_random tape_engine trampoline)
 (preprocess
  (pps base_quickcheck.ppx_quickcheck ppx_sexp_conv ppx_compare ppx_let)))
